### PR TITLE
new badge

### PR DESCRIPTION
**Pull request by ocefpaf**
Add AppVeyor badge

### CODE REVIEW

**Comment by ocefpaf** [comment]
@emiliom the two Travis-CI failure we had here were a notebooks coding lint and a URL timing out.

I fixed the coding lint and moved the linting to `allow_failures` b/c that is not something that should prevent us from merging a PR here.

The URL that is timing out is http://52.40.105.124:8080/odm2timeseries/soap/cuahsi_1_0/.wsdl from the notebook 2017-07-04-WOFpy_ulmo.ipynb (see the error below).

Unfortunately notebooks like this behave as integration tests and are bound to get stale quickly.
We can,

- ignore the error and always check the logs before merging;
- move that notebook to `allow_failures`;
- contact the service provider and try to fix it.

The failure does not prevent us from adding new notebooks nor publishing them in the website.

```python
URLError                                  Traceback (most recent call last)
<ipython-input-6-ce58befa5b5b> in <module>()
----> 1 siteinfo = ulmo.cuahsi.wof.get_site_info(wsdlurl, networkcd+':'+sitecd)

/home/filipe/miniconda3/envs/BiG-CZ/lib/python2.7/site-packages/ulmo/cuahsi/wof/core.pyc in get_site_info(wsdl_url, site_code, suds_cache)
     93         a python dict containing site information
     94     """
---> 95     suds_client = _get_client(wsdl_url, suds_cache)
     96 
     97     waterml_version = _waterml_version(suds_client)

/home/filipe/miniconda3/envs/BiG-CZ/lib/python2.7/site-packages/ulmo/cuahsi/wof/core.pyc in _get_client(wsdl_url, cache_duration)
    281     # Handle new or changed client request (create new client)
    282     if _suds_client is None or _suds_client.wsdl.url != wsdl_url:
--> 283         _suds_client = suds.client.Client(wsdl_url)
    284         if cache_duration is None:
    285             _suds_client.set_options(cache=None)

/home/filipe/miniconda3/envs/BiG-CZ/lib/python2.7/site-packages/suds/client.pyc in __init__(self, url, **kwargs)
    113         self.set_options(**kwargs)
    114         reader = DefinitionsReader(options, Definitions)
--> 115         self.wsdl = reader.open(url)
    116         plugins = PluginContainer(options.plugins)
    117         plugins.init.initialized(wsdl=self.wsdl)

/home/filipe/miniconda3/envs/BiG-CZ/lib/python2.7/site-packages/suds/reader.pyc in open(self, url)
    148         d = cache.get(id)
    149         if d is None:
--> 150             d = self.fn(url, self.options)
    151             cache.put(id, d)
    152         else:

/home/filipe/miniconda3/envs/BiG-CZ/lib/python2.7/site-packages/suds/wsdl.pyc in __init__(self, url, options)
    134         log.debug('reading WSDL at: %s ...', url)
    135         reader = DocumentReader(options)
--> 136         d = reader.open(url)
    137         root = d.root()
    138         WObject.__init__(self, root)

/home/filipe/miniconda3/envs/BiG-CZ/lib/python2.7/site-packages/suds/reader.pyc in open(self, url)
     72         d = cache.get(id)
     73         if d is None:
---> 74             d = self.download(url)
     75             cache.put(id, d)
     76         self.plugins.document.parsed(url=url, document=d.root())

/home/filipe/miniconda3/envs/BiG-CZ/lib/python2.7/site-packages/suds/reader.pyc in download(self, url)
     90             content = store.open(url)
     91         if content is None:
---> 92             fp = self.options.transport.open(Request(url))
     93             try:
     94                 content = fp.read()

/home/filipe/miniconda3/envs/BiG-CZ/lib/python2.7/site-packages/suds/transport/https.pyc in open(self, request)
     60     def open(self, request):
     61         self.addcredentials(request)
---> 62         return HttpTransport.open(self, request)
     63 
     64     def send(self, request):

/home/filipe/miniconda3/envs/BiG-CZ/lib/python2.7/site-packages/suds/transport/http.pyc in open(self, request)
     65             u2request = urllib2.Request(url)
     66             self.proxy = self.options.proxy
---> 67             return self.u2open(u2request)
     68         except urllib2.HTTPError, e:
     69             raise TransportError(str(e), e.code, e.fp)

/home/filipe/miniconda3/envs/BiG-CZ/lib/python2.7/site-packages/suds/transport/http.pyc in u2open(self, u2request)
    130             socket.setdefaulttimeout(tm)
    131             return url.open(u2request)
--> 132         return url.open(u2request, timeout=tm)
    133 
    134     def u2opener(self):

/home/filipe/miniconda3/envs/BiG-CZ/lib/python2.7/urllib2.pyc in open(self, fullurl, data, timeout)
    427             req = meth(req)
    428 
--> 429         response = self._open(req, data)
    430 
    431         # post-process response

/home/filipe/miniconda3/envs/BiG-CZ/lib/python2.7/urllib2.pyc in _open(self, req, data)
    445         protocol = req.get_type()
    446         result = self._call_chain(self.handle_open, protocol, protocol +
--> 447                                   '_open', req)
    448         if result:
    449             return result

/home/filipe/miniconda3/envs/BiG-CZ/lib/python2.7/urllib2.pyc in _call_chain(self, chain, kind, meth_name, *args)
    405             func = getattr(handler, meth_name)
    406 
--> 407             result = func(*args)
    408             if result is not None:
    409                 return result

/home/filipe/miniconda3/envs/BiG-CZ/lib/python2.7/urllib2.pyc in http_open(self, req)
   1226 
   1227     def http_open(self, req):
-> 1228         return self.do_open(httplib.HTTPConnection, req)
   1229 
   1230     http_request = AbstractHTTPHandler.do_request_

/home/filipe/miniconda3/envs/BiG-CZ/lib/python2.7/urllib2.pyc in do_open(self, http_class, req, **http_conn_args)
   1196         except socket.error, err: # XXX what error?
   1197             h.close()
-> 1198             raise URLError(err)
   1199         else:
   1200             try:

URLError: <urlopen error timed out>
```

**Comment by emiliom** [comment]
Thanks. @lsetiawan and I will follow up on Monday.

**Comment by emiliom** [comment]
@lsetiawan - I'm following up on @ocefpaf's comments:

> The URL that is timing out is http://52.40.105.124:8080/odm2timeseries/soap/cuahsi_1_0/.wsdl from the notebook 2017-07-04-WOFpy_ulmo.ipynb (see the error below).

Is this even the current IP address of our AWS instance?? If it is, is that a WOFpy endpoint that is supposed to be working now, or -- as I suspect -- is it one that's now decommissioned?


> Unfortunately notebooks like this behave as integration tests and are bound to get stale quickly.
> We can,
> - ignore the error and always check the logs before merging;
> - move that notebook to allow_failures;
> - contact the service provider and try to fix it.
>
> The failure does not prevent us from adding new notebooks nor publishing them in the website.

If we see errors in a notebook log, we should take a quick look to see if it's something we can fix easily (including contacting service providers if we know them). If that's the case, or it's outside our control, we'll ignore it; if it's hopeless, let's move the notebook to `allow_failures`.

Does that sound good?

**Comment by emiliom** [comment]
Oh, and we can merge this PR, right?

**Comment by lsetiawan** [comment]
For the URL it should be http://54.186.36.247:8080/mysqlodm2timeseries/soap/cuahsi_1_0/.wsdl

**Comment by ocefpaf** [comment]
> For the URL it should be http://54.186.36.247:8080/mysqlodm2timeseries/soap/cuahsi_1_0/.wsdl

 Let me try that before we merge this.

> Oh, and we can merge this PR, right?

Note that notebooks failures here will be common due to the large number of software and services they integrate.  In the IOOS site we use that as a testing layer and try to fix whatever we can, but sometimes we will have to merge failing notebooks to get a new one published.

**Comment by ocefpaf** [comment]
@lsetiawan I guess that more changes are needed: http://nbviewer.jupyter.org/gist/ocefpaf/282de32a99d8bd1937bda670e5d5ec58

**Comment by lsetiawan** [comment]
URL: http://54.186.36.247:8080/mysqlodm2timeseries/soap/cuahsi_1_1/.wsdl

``` python
# 'network code'
networkcd = 'mysqlodm2timeseries'
```

```python
siteinfo['series']['mysqlodm2timeseries:USU33'].keys()
```

```
siteinfo['series']['mysqlodm2timeseries:USU33']
```

**Comment by emiliom** [comment]
> @lsetiawan I guess that more changes are needed: http://nbviewer.jupyter.org/gist/ocefpaf/282de32a99d8bd1937bda670e5d5ec58

@lsetiawan We can ignore that for now. But, let's change the notebook to hit the `soap/cuahsi_1_1` endpoint, not `soap/cuahsi_1_0`. We know 1.0 may have a bunch of problems that we won't address any time soon.

**Comment by ocefpaf** [comment]
Thanks @lsetiawan! https://github.com/BiG-CZ/notebook_data_demo/pull/17#issuecomment-340613281 is implemented in 
https://github.com/BiG-CZ/notebook_data_demo/pull/17/commits/4b741685587071a2afd50bb21139d29dd0a2453b and everything was OK locally.

**Pull request merged**
