### PR TITLE
first commit

### PR DESCRIPTION
**Pull request by ocefpaf**
Reviewing this PR will be like drinking from a firehouse. I recommend just merging it, and the next ones, until we get a functional webpage. After that reviews will be easier.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Wow! That was fast :smile:

**Comment by emiliom** [comment]
Yes sir. Thanks!

We aim to please.

**Comment by ocefpaf** [comment]
I am struggling to adapt the theme, but I should have more PRs ready before the end of the week.

**Comment by emiliom** [comment]
No problem.

**Pull request merged**
